[main]
certname = utn-devops.localhost
server = utn-devops.localhost
environment = production
runinterval = 30m
vardir = /opt/puppetlabs/puppet/cache
logdir = /var/log/puppetlabs/puppet
rundir = /var/run/puppetlabs

[agent]
report = true
pluginsync = true
