pipeline {
  agent any
  tools { nodejs 'node22' }
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '3'))
    timestamps()
  }
  triggers { pollSCM('* * * * *') }

  environment {
    APP_REPO   = 'https://github.com/LautaroRecabarren/utn-devops-app.git'
    APP_BRANCH = 'unidad-4-jenkins'
    APP_DIR    = 'app'
  }

  stages {
    stage('Checkout infra (self)'){ steps { checkout scm } }
    stage('Checkout app'){
      steps { dir(APP_DIR){ git url: "${env.APP_REPO}", branch: "${env.APP_BRANCH}" } }
    }
    stage('Install deps'){ steps { dir(APP_DIR){ sh 'npm ci' } } }
    stage('Unit tests'){ steps { dir(APP_DIR){ sh 'npm test --silent' } } }
  }

  post {
    success { echo 'Build & tests OK' }
    failure { echo 'Build FAILED' }
  }
}
